### ISSUE TITLE
HTML/CSS

### ISSUE THREAD

**Issue by TimofeiShpak** [safym/FE-school-homework-1#1]
https://github.com/safym/FE-school-homework-1/blob/8952af7cebcac682f9d4b19c78b2f56e64b8eae6/empty-page/index.html#L13

замечание касательно button--style--primary,
"--" используется для альтернативного нейминга стилей, просьба использовать только "_" для модификаторов
в рекомендация по написанию кода в пункте про БЭМ указано что нужно использовать только классическое наименование

также просьба поправить это в других файлах, для остальных модификаторов

**Comment by TimofeiShpak** [comment]
https://github.com/safym/FE-school-homework-1/blob/8952af7cebcac682f9d4b19c78b2f56e64b8eae6/navigation/index.html#L15

здесь очень сложный класс, button__nav можно выделить в отдельный элемент
правильнее будет class="header__button button button__nav button__nav_active"


button--style--dropdown - тоже описывает не состояние, а другой элемент, поэтому правильнее button__dropdown

**Comment by safym** [comment]
1. Исправила классы по BEM согласно классическому наименованию во всех случаях.
2. Изменила nav и dropdown модификатор кнопки на элемент.
